spring.application.name=CertificateVerification
spring.datasource.url=jdbc:mysql://localhost:3306/certificate_db
spring.datasource.username=root
spring.datasource.password=Rio3341
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
